[package]
name = "photo-dedupe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0.79", features = ["backtrace"]}
indicatif = "0.17.7"
roxmltree = "0.19.0"
